baseURL = 'https://scarlet-tobar.github.io/'
languageCode = 'es'
title = 'Scarlet Tobar Nuñez'
theme = "awesome-identity"

defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true

[languages]
	[languages.en]
		contentDir = 'content/en'
		## Profile Configurations
		[languages.en.params.profile]
		  portrait = "p.png"
		  firstname = "Scarlet"
		  lastname = "Tobar"
		  title = "Computer Engineer"
		  bio = """
		  Computer Engineer from Universidad Católica del Norte.
		  Español, English.
		  I maintain Chilemasto.
		  I have experience with Wordpress, C++, Python, Scheme, GNU/Linux system administration, Fediverse.
    		  Please use contact info below for professional purposes.
    """


		## Footer Configurations
		[languages.en.params.footer]
		  copyright = "©Scarlet Tobar Núñez"
		  poweredBy = false


		[languages.en.params.contacts]
		  email = "scarlettobarnunez@gmail.com"
		  github = "scarlet-tobar"
		  linkedin = "scarlet-tobar"
		 
		[[languages.en.params.actions]]
		  name = "Chilemasto"
		  url = "https://home.chilemasto.casa"

		[[languages.en.params.actions]]
		  name = "CV"
		  url = "https://raw.githubusercontent.com/scarlet-tobar/scarlet-tobar.github.io/main/static/CV-EN.pdf"
		
	[languages.es]
		contentDir= 'content/es'
		## Profile Configurations
		[languages.es.params.profile]
		  portrait = "p.png"
		  firstname = "Scarlet"
		  lastname = "Tobar"
		  title = "Ingeniera Civil en Computación e Informática"
		  bio = """
		  Ingeniera Civil en Computación e Informática egresada la Universidad Católica del Norte.
		  Español, English
		  Administro Chilemasto.
		  Tengo experiencia con Wordpress, C++, Python, Scheme, administración de sistemas GNU/Linux, Fediverso.
    		  Por favor use la información de contacto abajo para contacto profesional.
    """


		## Footer Configurations
		[languages.es.params.footer]
		  copyright = "©Scarlet Tobar Núñez"
		  poweredBy = false


		[languages.es.params.contacts]
		  email = "scarlettobarnunez@gmail.com"
		  github = "scarlet-tobar"
		  linkedin = "scarlet-tobar"

		[[languages.es.params.actions]]
		  name = "Chilemasto"
		  url = "https://home.chilemasto.casa"
		  
		[[languages.es.params.actions]]
		  name = "CV"
		  url = "https://raw.githubusercontent.com/scarlet-tobar/scarlet-tobar.github.io/main/static/CV-ES.pdf"
